### ISSUE TITLE
"ModuleNotFoundError: No module named 'pyqtgraph'" in OSGeo4W installs

### ISSUE THREAD

**Issue by anitagraser** [timlinux/QGISAnimationWorkbench#78]
I installed all pyqt libraries available via OSGeo4W but no luck: 

```
Couldn't load plugin 'animation_workbench' 

ModuleNotFoundError: No module named 'pyqtgraph' 
Traceback (most recent call last):
  File "J:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 404, in loadPlugin
    __import__(packageName)
  File "J:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 891, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\__init__.py", line 29, in 
    from .animation_workbench import AnimationWorkbench
  File "J:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 891, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\animation_workbench.py", line 55, in 
    FORM_CLASS = get_ui_class("animation_workbench_base.ui")
  File "C:\Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\utilities.py", line 84, in get_ui_class
    return uic.loadUiType(ui_file_path)[0]
  File "J:\OSGeo4W/apps/qgis-dev/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "J:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 633, in 
  File "J:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 891, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\easing_preview.py", line 17, in 
    from pyqtgraph import PlotWidget
  File "J:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 891, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyqtgraph'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.35.0-Master Master, 5ac90ce54c 

Python Path:
J:/OSGeo4W/apps/qgis-dev/./python
C:/Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
J:/OSGeo4W/apps/qgis-dev/./python/plugins
J:\OSGeo4W\apps\gdal-dev\lib\site-packages
F:\Documents
J:\OSGeo4W\bin\python39.zip
J:\OSGeo4W\apps\Python39\DLLs
J:\OSGeo4W\apps\Python39\lib
J:\OSGeo4W\bin
J:\OSGeo4W\apps\Python39
J:\OSGeo4W\apps\Python39\lib\site-packages
C:/Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python
..
..
..
..
C:\Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\anita\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\anita\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
.
```

**Comment by timlinux** [comment]
Thanks for this @anitagraser 

I think I will just disable the graph plots if you dont have the needed libs. I though pyqtgraph came bundled on windows.

Regards

Tim

**Comment by darcman0** [comment]
I installed the pluging in my window pc but it doesn't run: 

```
Impossible de charger l'extension 'animation_workbench' 

ModuleNotFoundError: No module named 'pyqtgraph' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\__init__.py", line 29, in 
    from .animation_workbench import AnimationWorkbench
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\animation_workbench.py", line 55, in 
    FORM_CLASS = get_ui_class("animation_workbench_base.ui")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\utilities.py", line 84, in get_ui_class
    return uic.loadUiType(ui_file_path)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages\PyQt5\uic\__init__.py", line 207, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 633, in 
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\easing_preview.py", line 17, in 
    from pyqtgraph import PlotWidget # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyqtgraph'


Version de Python : 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
Version de QGIS : 3.34.9-Prizren Prizren, cbbc7bdf 

Chemin Python :
C:/PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.9\apps\grass\grass83\etc\python
C:\Users\hp\Documents
C:\Program Files\QGIS 3.34.9\bin\python312.zip
C:\PROGRA~1\QGIS33~1.9\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib
C:\Program Files\QGIS 3.34.9\bin
C:\Users\hp\AppData\Roaming\Python\Python312\site-packages
C:\PROGRA~1\QGIS33~1.9\apps\Python312
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by VxTedxV** [comment]
Same issue with Macport install of QGis (3.44) with python 3.13

**Comment by timlinux** [comment]
> Same issue with Macport install of QGis (3.44) with python 3.13

Could you try with this build: https://plugins.qgis.org/plugins/animation_workbench/version/1.4/

**Comment by VxTedxV** [comment]
Sorry for delay.
It doesn't work at all.
In QGis, I uninstalled the plugin, tried to reinstall with the last version (08/03/26) but while installing, it opens a second instance of QGis that crash. The first instance of QGis shows these messages :
`2026-03-14T16:56:52     CRITICAL    Invalid Data Source : /-m is not a valid or recognized data source.`
`2026-03-14T16:56:52     CRITICAL    Invalid Data Source : /pip is not a valid or recognized data source.`
`2026-03-14T16:56:52     CRITICAL    Invalid Data Source : /install is not a valid or recognized data source.`
`2026-03-14T16:56:52     CRITICAL    Invalid Data Source : /pyqtgraph is not a valid or recognized data source.`

**Comment by geomenke** [comment]
I'm experiencing the same issue as @VxTedxV describes above in QGIS 3.44.
