### ISSUE TITLE
"ModuleNotFoundError: No module named 'pyqtgraph' " 

### ISSUE THREAD

**Issue by kapildevadk** [timlinux/QGISAnimationWorkbench#80]
Even I have installed "pyqtgraph" pip library, the following error popups when installing plugin 'animation_workbench' .

Couldn't load plugin 'animation_workbench' 

ModuleNotFoundError: No module named 'pyqtgraph' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\__init__.py", line 29, in 
    from .animation_workbench import AnimationWorkbench
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\animation_workbench.py", line 55, in 
    FORM_CLASS = get_ui_class("animation_workbench_base.ui")
  File "C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\utilities.py", line 84, in get_ui_class
    return uic.loadUiType(ui_file_path)[0]
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS32~1.15\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 633, in 
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\animation_workbench\easing_preview.py", line 17, in 
    from pyqtgraph import PlotWidget
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyqtgraph'

Python version: 3.9.18 (heads/master:c290dc6, Jan 14 2024, 01:36:02) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.28.15-Firenze Firenze, 252ad49ddc 

Python Path:
C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\whitebox_workflows_for_qgis
C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:/PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python
C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.15\apps\grass\grass83\etc\python
C:\WINDOWS\System32
C:\Program Files\QGIS 3.28.15\bin\python39.zip
C:\PROGRA~1\QGIS32~1.15\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.15\apps\Python39\lib
C:\Program Files\QGIS 3.28.15\bin
C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.15\apps\Python39
C:\PROGRA~1\QGIS32~1.15\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.15\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.15\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.15\apps\Python39\lib\site-packages\Pythonwin
C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by timlinux** [comment]
@kapildevadk @Millgor thank you for your reports - I have made a fix, I will release an update package shortly.

**Comment by styrke10** [comment]
Has the update package with the fix been released? I have the same problem using version 1.2 from April 17....
